import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"; // We'll create this file next

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "v0.app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Add suppressHydrationWarning for next-themes
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* All providers are now cleanly wrapped in a single component */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
